INSERT INTO social.tweets (user_id, tweet_text)
VALUES
(1, 'Just started using Twitter! Excited to be here. #FirstTweet'),
(2, 'Loving the new book I started reading, highly recommend it! #ReadingTime'),
(3, 'Can''t wait for the weekend. More coding ahead! #TechLife'),
(4, 'Exploring the city today. Any good food spots in San Francisco? #Travel'),
(5, 'Who else loves the beach? So relaxing! #BeachVibes'),
(6, 'Amazing sunset tonight! Nature is the best artist. #SunsetLover'),
(7, 'New workout routine is kicking my butt! But I feel stronger already. #FitnessGoals'),
(8, 'Looking for good podcasts on business. Any recommendations? #EntrepreneurLife'),
(9, 'Feeling grateful for my family and friends. #Thankful'),
(10, 'Let''s make today a productive one! #MotivationMonday'),
(11, 'Coffee and coding, the best combination. #DeveloperLife'),
(12, 'Had a great time at the concert last night! #LiveMusic'),
(13, 'Finally finished a new blog post. Check it out! #WriterLife'),
(14, 'Always a good day when there''s a new episode of my favorite show. #TVTime'),
(15, 'Exploring new coffee spots in the city! Any recommendations? #CoffeeLover'),
(1, 'Feeling great after a long run this morning! #MorningExercise'),
(2, 'Just tried the best pizza in town. Can''t stop thinking about it! #FoodieAdventures'),
(3, 'Excited for the new tech release coming this week! #TechNews'),
(4, 'Looking for some fun activities to do this weekend. Suggestions? #WeekendPlans'),
(5, 'Tried a new yoga class today. My flexibility is improving! #YogaJourney'),
(6, 'Feeling so inspired after attending today''s workshop. #LearningEveryDay'),
(7, 'It''s a rainy day, perfect for a cozy movie marathon. #RainyDayVibes'),
(8, 'Just hit 50 followers! Thanks for the support! #Grateful'),
(9, 'Had a blast at the charity event last night. #GivingBack'),
(10, 'Can''t believe it''s already Thursday. The week is flying by! #TimeFlies'),
(11, 'Sometimes, the best ideas come from a walk in nature. #Inspiration'),
(12, 'Feeling accomplished after finishing a big project at work. #WorkGoals'),
(13, 'I love starting my day with a good cup of coffee and a good book. #MorningRoutine'),
(14, 'Just saw an amazing documentary about space. Highly recommend it! #SpaceExploration'),
(15, 'Working on a new creative project. Excited to share it soon! #CreativeMind');
