INSERT INTO social.hashtags (hashtag_name, description)
VALUES
    ('#FirstTweet', 'A hashtag for people sharing their first tweet on Twitter'),
    ('#ReadingTime', 'For posts related to books and reading'),
    ('#TechLife', 'For posts related to technology and tech enthusiasts'),
    ('#Travel', 'Used for sharing travel experiences and adventures'),
    ('#BeachVibes', 'For posts about enjoying the beach and ocean life'),
    ('#SunsetLover', 'For posts about appreciating sunsets and beautiful skies'),
    ('#FitnessGoals', 'For posts related to fitness, goals, and workouts'),
    ('#EntrepreneurLife', 'For entrepreneurs to share their journey and experiences'),
    ('#Thankful', 'For expressing gratitude and appreciation'),
    ('#MotivationMonday', 'A motivational hashtag used to kickstart the week'),
    ('#DeveloperLife', 'For developers to share their projects and coding experiences'),
    ('#LiveMusic', 'For posts related to attending live concerts or music events'),
    ('#WriterLife', 'For writers to share their creative process and work'),
    ('#TVTime', 'For posts about watching TV shows or series'),
    ('#CoffeeLover', 'For those who love coffee and share coffee-related content'),
    ('#MorningExercise', 'For sharing fitness activities and workouts done in the morning'),
    ('#FoodieAdventures', 'For food lovers to share culinary experiences and recommendations'),
    ('#TechNews', 'For sharing the latest news and trends in the tech industry'),
    ('#WeekendPlans', 'For sharing plans or activities for the weekend'),
    ('#YogaJourney', 'For posts related to yoga practice and personal growth'),
    ('#LearningEveryDay', 'For sharing educational content and personal learning experiences'),
    ('#RainyDayVibes', 'For posts reflecting the mood or activities on a rainy day'),
    ('#Grateful', 'For expressing feelings of gratitude and thankfulness'),
    ('#GivingBack', 'For sharing charitable acts, donations, and giving back to the community'),
    ('#TimeFlies', 'For posts reflecting how quickly time passes'),
    ('#Inspiration', 'For sharing inspiring thoughts, quotes, and ideas'),
    ('#WorkGoals', 'For sharing professional goals, achievements, and productivity tips'),
    ('#MorningRoutine', 'For posts about morning routines and how people start their day'),
    ('#SpaceExploration', 'For posts related to space, astronomy, and exploration'),
    ('#CreativeMind', 'For those who share their creative ideas and projects');

