SET client_encoding TO 'UTF8';
INSERT INTO social.comments (tweet_id, user_id, comment_text)
VALUES
(1, 2, 'Welcome to Twitter! Excited for you to join! #FirstTweet'),
(2, 3, 'That sounds awesome! What book are you reading? #ReadingTime'),
(3, 4, 'Weekend coding sounds great! What’s your project about? #TechLife'),
(4, 5, 'I know some great spots! You should check out Mission District for food. #Travel'),
(5, 6, 'I love the beach too! Do you prefer the ocean or just the sand? #BeachVibes'),
(6, 7, 'Sunsets are so magical! Do you have a favorite sunset view? #SunsetLover'),
(7, 8, 'Nice job on the workout! Keep it up! How often do you work out? #FitnessGoals'),
(8, 9, 'I’ve got some podcast recommendations! “How I Built This” is amazing! #EntrepreneurLife'),
(9, 10, 'Feeling grateful is the key! What are you most thankful for today? #Thankful'),
(10, 11, 'Let’s crush the week! What’s on your to-do list for today? #MotivationMonday'),
(11, 12, 'Coffee and coding are the perfect combo! What project are you working on? #DeveloperLife'),
(12, 13, 'Sounds like an amazing concert! What genre of music was it? #LiveMusic'),
(13, 14, 'I can’t wait to read your new blog! What’s it about? #WriterLife'),
(14, 15, 'TV time is always fun! What show are you watching right now? #TVTime'),
(15, 1, 'I love exploring new coffee places too! Any recommendations for a good latte? #CoffeeLover'),

(1, 1, 'Thanks! Looking forward to meeting new people here. #FirstTweet'),
(2, 2, 'I’m reading “Atomic Habits.” It’s a great read! #ReadingTime'),
(3, 3, 'I’m building a new app for the weekend. Excited to share soon! #TechLife'),
(4, 6, 'I’ll definitely check it out! Love discovering hidden gems. #Travel'),
(5, 7, 'I’m all about the ocean! Can’t beat a good beach walk. #BeachVibes'),
(6, 8, 'Totally agree! The colors during sunset are amazing. #SunsetLover'),
(7, 9, 'I work out 3 times a week! Focused on building strength. #FitnessGoals'),
(8, 10, 'I’ll definitely check it out. Thanks for the recommendation! #EntrepreneurLife'),
(9, 11, 'I’m most thankful for my health and family. What about you? #Thankful'),
(10, 12, 'I’ve got a lot planned! Just trying to stay productive. #MotivationMonday'),
(11, 13, 'I’m working on a new website for a client. Lots of coding! #DeveloperLife'),
(12, 14, 'It was a rock concert! Amazing vibe! #LiveMusic'),
(13, 15, 'My new blog post is about productivity hacks. Can’t wait for you to read it! #WriterLife'),
(14, 1, 'I’m watching a new Netflix series. What about you? #TVTime'),
(15, 2, 'I’ll definitely try that! I’m a huge fan of good lattes. #CoffeeLover');
